/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_kneo_libsimplefft_Convolution */

#ifndef _Included_com_github_kneo_libsimplefft_Convolution
#define _Included_com_github_kneo_libsimplefft_Convolution
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_kneo_libsimplefft_Convolution
 * Method:    init
 * Signature: (II[B[B)I
 */
JNIEXPORT jint JNICALL Java_com_github_kneo_libsimplefft_Convolution_init__II_3B_3B
  (JNIEnv *, jclass, jint, jint, jbyteArray, jbyteArray);

/*
 * Class:     com_github_kneo_libsimplefft_Convolution
 * Method:    init
 * Signature: (II[S[S)I
 */
JNIEXPORT jint JNICALL Java_com_github_kneo_libsimplefft_Convolution_init__II_3S_3S
  (JNIEnv *, jclass, jint, jint, jshortArray, jshortArray);

/*
 * Class:     com_github_kneo_libsimplefft_Convolution
 * Method:    init
 * Signature: (II[I[I)I
 */
JNIEXPORT jint JNICALL Java_com_github_kneo_libsimplefft_Convolution_init__II_3I_3I
  (JNIEnv *, jclass, jint, jint, jintArray, jintArray);

/*
 * Class:     com_github_kneo_libsimplefft_Convolution
 * Method:    init
 * Signature: (II[F[F)I
 */
JNIEXPORT jint JNICALL Java_com_github_kneo_libsimplefft_Convolution_init__II_3F_3F
  (JNIEnv *, jclass, jint, jint, jfloatArray, jfloatArray);

/*
 * Class:     com_github_kneo_libsimplefft_Convolution
 * Method:    init
 * Signature: (II[D[D)I
 */
JNIEXPORT jint JNICALL Java_com_github_kneo_libsimplefft_Convolution_init__II_3D_3D
  (JNIEnv *, jclass, jint, jint, jdoubleArray, jdoubleArray);

/*
 * Class:     com_github_kneo_libsimplefft_Convolution
 * Method:    perform
 * Signature: (I[B[B)V
 */
JNIEXPORT void JNICALL Java_com_github_kneo_libsimplefft_Convolution_perform__I_3B_3B
  (JNIEnv *, jclass, jint, jbyteArray, jbyteArray);

/*
 * Class:     com_github_kneo_libsimplefft_Convolution
 * Method:    perform
 * Signature: (I[S[S)V
 */
JNIEXPORT void JNICALL Java_com_github_kneo_libsimplefft_Convolution_perform__I_3S_3S
  (JNIEnv *, jclass, jint, jshortArray, jshortArray);

/*
 * Class:     com_github_kneo_libsimplefft_Convolution
 * Method:    perform
 * Signature: (I[I[I)V
 */
JNIEXPORT void JNICALL Java_com_github_kneo_libsimplefft_Convolution_perform__I_3I_3I
  (JNIEnv *, jclass, jint, jintArray, jintArray);

/*
 * Class:     com_github_kneo_libsimplefft_Convolution
 * Method:    perform
 * Signature: (I[F[F)V
 */
JNIEXPORT void JNICALL Java_com_github_kneo_libsimplefft_Convolution_perform__I_3F_3F
  (JNIEnv *, jclass, jint, jfloatArray, jfloatArray);

/*
 * Class:     com_github_kneo_libsimplefft_Convolution
 * Method:    perform
 * Signature: (I[D[D)V
 */
JNIEXPORT void JNICALL Java_com_github_kneo_libsimplefft_Convolution_perform__I_3D_3D
  (JNIEnv *, jclass, jint, jdoubleArray, jdoubleArray);

/*
 * Class:     com_github_kneo_libsimplefft_Convolution
 * Method:    destroy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_github_kneo_libsimplefft_Convolution_destroy
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
