/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_kneo_libsimplefft_FFT */

#ifndef _Included_com_github_kneo_libsimplefft_FFT
#define _Included_com_github_kneo_libsimplefft_FFT
#ifdef __cplusplus
extern "C" {
#endif
#undef com_github_kneo_libsimplefft_FFT_SINGLE_PRECISION
#define com_github_kneo_libsimplefft_FFT_SINGLE_PRECISION 0L
#undef com_github_kneo_libsimplefft_FFT_DOUBLE_PRECISION
#define com_github_kneo_libsimplefft_FFT_DOUBLE_PRECISION 1L
#undef com_github_kneo_libsimplefft_FFT_INTEGER_16_BIT
#define com_github_kneo_libsimplefft_FFT_INTEGER_16_BIT 2L
#undef com_github_kneo_libsimplefft_FFT_INTEGER_8_BIT
#define com_github_kneo_libsimplefft_FFT_INTEGER_8_BIT 3L
#undef com_github_kneo_libsimplefft_FFT_INTEGER_32_BIT
#define com_github_kneo_libsimplefft_FFT_INTEGER_32_BIT 4L
/*
 * Class:     com_github_kneo_libsimplefft_FFT
 * Method:    init
 * Signature: (IIIZ)I
 */
JNIEXPORT jint JNICALL Java_com_github_kneo_libsimplefft_FFT_init
  (JNIEnv *, jclass, jint, jint, jint, jboolean);

/*
 * Class:     com_github_kneo_libsimplefft_FFT
 * Method:    perform
 * Signature: (I[B[B)V
 */
JNIEXPORT void JNICALL Java_com_github_kneo_libsimplefft_FFT_perform__I_3B_3B
  (JNIEnv *, jclass, jint, jbyteArray, jbyteArray);

/*
 * Class:     com_github_kneo_libsimplefft_FFT
 * Method:    perform
 * Signature: (I[S[S)V
 */
JNIEXPORT void JNICALL Java_com_github_kneo_libsimplefft_FFT_perform__I_3S_3S
  (JNIEnv *, jclass, jint, jshortArray, jshortArray);

/*
 * Class:     com_github_kneo_libsimplefft_FFT
 * Method:    perform
 * Signature: (I[I[I)V
 */
JNIEXPORT void JNICALL Java_com_github_kneo_libsimplefft_FFT_perform__I_3I_3I
  (JNIEnv *, jclass, jint, jintArray, jintArray);

/*
 * Class:     com_github_kneo_libsimplefft_FFT
 * Method:    perform
 * Signature: (I[F[F)V
 */
JNIEXPORT void JNICALL Java_com_github_kneo_libsimplefft_FFT_perform__I_3F_3F
  (JNIEnv *, jclass, jint, jfloatArray, jfloatArray);

/*
 * Class:     com_github_kneo_libsimplefft_FFT
 * Method:    perform
 * Signature: (I[D[D)V
 */
JNIEXPORT void JNICALL Java_com_github_kneo_libsimplefft_FFT_perform__I_3D_3D
  (JNIEnv *, jclass, jint, jdoubleArray, jdoubleArray);

/*
 * Class:     com_github_kneo_libsimplefft_FFT
 * Method:    destroy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_github_kneo_libsimplefft_FFT_destroy
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
